/// A2A Task handling — the core unit of work in the A2A protocol.
///
/// External agents send tasks to engram, specifying a skill and a message.
/// Tasks go through state transitions: submitted -> working -> completed/failed.

/// Task states per A2A spec.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TaskState {
    Submitted,
    Working,
    Completed,
    Failed,
    Canceled,
    InputRequired,
}

/// An A2A task request (POST /tasks/send).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskRequest {
    /// Unique task ID (generated by caller or server)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Which skill to invoke
    pub skill_id: String,
    /// The message to process
    pub message: TaskMessage,
    /// Optional metadata
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// Webhook URL for push notifications
    #[serde(skip_serializing_if = "Option::is_none")]
    pub push_notification_url: Option<String>,
}

/// A message within a task.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskMessage {
    /// The role: "user" or "agent"
    pub role: String,
    /// Content parts
    pub parts: Vec<MessagePart>,
}

/// A part of a message.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum MessagePart {
    /// Plain text content
    #[serde(rename = "text")]
    Text { text: String },
    /// Structured data
    #[serde(rename = "data")]
    Data { data: serde_json::Value },
    /// File reference
    #[serde(rename = "file")]
    File {
        #[serde(rename = "mimeType")]
        mime_type: String,
        name: String,
    },
}

impl TaskMessage {
    /// Create a simple text message from a user.
    pub fn user_text(text: &str) -> Self {
        TaskMessage {
            role: "user".to_string(),
            parts: vec![MessagePart::Text { text: text.to_string() }],
        }
    }

    /// Create a simple text message from the agent.
    pub fn agent_text(text: &str) -> Self {
        TaskMessage {
            role: "agent".to_string(),
            parts: vec![MessagePart::Text { text: text.to_string() }],
        }
    }

    /// Extract all text from parts.
    pub fn text(&self) -> String {
        self.parts
            .iter()
            .filter_map(|p| match p {
                MessagePart::Text { text } => Some(text.as_str()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join(" ")
    }

    /// Extract first data part, if any.
    pub fn data(&self) -> Option<&serde_json::Value> {
        self.parts.iter().find_map(|p| match p {
            MessagePart::Data { data } => Some(data),
            _ => None,
        })
    }
}

/// An artifact produced by a completed task.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Artifact {
    /// MIME type of the artifact
    #[serde(rename = "type")]
    pub artifact_type: String,
    /// The artifact data
    pub data: serde_json::Value,
    /// Optional name
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl Artifact {
    /// Create a JSON artifact.
    pub fn json(data: serde_json::Value) -> Self {
        Artifact {
            artifact_type: "application/json".to_string(),
            data,
            name: None,
        }
    }

    /// Create a named JSON artifact.
    pub fn json_named(name: &str, data: serde_json::Value) -> Self {
        Artifact {
            artifact_type: "application/json".to_string(),
            data,
            name: Some(name.to_string()),
        }
    }
}

/// An A2A task response.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskResponse {
    /// Task ID
    pub id: String,
    /// Current state
    pub status: TaskStatus,
    /// Artifacts produced (present when completed)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub artifacts: Option<Vec<Artifact>>,
    /// State transition history
    #[serde(skip_serializing_if = "Option::is_none")]
    pub history: Option<Vec<TaskStatus>>,
}

/// Task status with optional message.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskStatus {
    pub state: TaskState,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<TaskMessage>,
    /// Timestamp (unix millis)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<u64>,
}

impl TaskResponse {
    /// Create a completed task response with artifacts.
    pub fn completed(id: &str, artifacts: Vec<Artifact>) -> Self {
        TaskResponse {
            id: id.to_string(),
            status: TaskStatus {
                state: TaskState::Completed,
                message: None,
                timestamp: Some(now_millis()),
            },
            artifacts: Some(artifacts),
            history: None,
        }
    }

    /// Create a failed task response.
    pub fn failed(id: &str, error: &str) -> Self {
        TaskResponse {
            id: id.to_string(),
            status: TaskStatus {
                state: TaskState::Failed,
                message: Some(TaskMessage::agent_text(error)),
                timestamp: Some(now_millis()),
            },
            artifacts: None,
            history: None,
        }
    }

    /// Create a working (in-progress) response.
    pub fn working(id: &str, message: &str) -> Self {
        TaskResponse {
            id: id.to_string(),
            status: TaskStatus {
                state: TaskState::Working,
                message: Some(TaskMessage::agent_text(message)),
                timestamp: Some(now_millis()),
            },
            artifacts: None,
            history: None,
        }
    }
}

fn now_millis() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// Generate a task ID.
pub fn generate_task_id() -> String {
    use std::hash::{Hash, Hasher};
    let ts = now_millis();
    let mut h = std::collections::hash_map::DefaultHasher::new();
    ts.hash(&mut h);
    std::thread::current().id().hash(&mut h);
    let rand = h.finish();
    format!("task-{ts:x}-{rand:08x}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_text_message() {
        let msg = TaskMessage::user_text("What is Rust?");
        assert_eq!(msg.role, "user");
        assert_eq!(msg.text(), "What is Rust?");
    }

    #[test]
    fn agent_text_message() {
        let msg = TaskMessage::agent_text("Rust is a systems language.");
        assert_eq!(msg.role, "agent");
        assert_eq!(msg.text(), "Rust is a systems language.");
    }

    #[test]
    fn multi_part_text() {
        let msg = TaskMessage {
            role: "user".to_string(),
            parts: vec![
                MessagePart::Text { text: "Hello".to_string() },
                MessagePart::Text { text: "World".to_string() },
            ],
        };
        assert_eq!(msg.text(), "Hello World");
    }

    #[test]
    fn data_extraction() {
        let msg = TaskMessage {
            role: "user".to_string(),
            parts: vec![
                MessagePart::Text { text: "store this".to_string() },
                MessagePart::Data { data: serde_json::json!({"entity": "Rust"}) },
            ],
        };
        let data = msg.data().unwrap();
        assert_eq!(data["entity"], "Rust");
    }

    #[test]
    fn completed_response() {
        let resp = TaskResponse::completed("t1", vec![
            Artifact::json(serde_json::json!({"result": "ok"})),
        ]);
        assert_eq!(resp.status.state, TaskState::Completed);
        assert_eq!(resp.artifacts.unwrap().len(), 1);
    }

    #[test]
    fn failed_response() {
        let resp = TaskResponse::failed("t2", "skill not found");
        assert_eq!(resp.status.state, TaskState::Failed);
        assert_eq!(resp.status.message.unwrap().text(), "skill not found");
    }

    #[test]
    fn task_request_json() {
        let req = TaskRequest {
            id: Some("t3".to_string()),
            skill_id: "query-knowledge".to_string(),
            message: TaskMessage::user_text("What is Rust?"),
            metadata: None,
            push_notification_url: None,
        };
        let json = serde_json::to_string(&req).unwrap();
        let parsed: TaskRequest = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.skill_id, "query-knowledge");
    }

    #[test]
    fn generate_unique_ids() {
        let id1 = generate_task_id();
        let id2 = generate_task_id();
        assert!(id1.starts_with("task-"));
        // IDs are unique (at least from the timestamp component)
        // Note: in tight loops they might match, so we just check format
        assert!(id1.len() > 10);
        let _ = id2;
    }

    #[test]
    fn artifact_json() {
        let art = Artifact::json_named("results", serde_json::json!({"count": 5}));
        assert_eq!(art.name.as_deref(), Some("results"));
        assert_eq!(art.artifact_type, "application/json");
    }

    #[test]
    fn task_state_serialization() {
        let json = serde_json::to_string(&TaskState::Completed).unwrap();
        assert_eq!(json, "\"completed\"");
        let state: TaskState = serde_json::from_str("\"failed\"").unwrap();
        assert_eq!(state, TaskState::Failed);
    }
}
